"""empty message

Revision ID: 1c7e53b54117
Revises: 7eff50944384
Create Date: 2023-02-09 12:14:10.964099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7e53b54117'
down_revision = '7eff50944384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_request', schema=None) as batch_op:
        batch_op.drop_column('sender')

    # ### end Alembic commands ###
